# Generated by Django 3.1.5 on 2021-05-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20210512_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel',
            old_name='ques',
            new_name='question',
        ),
    ]
